#ifndef PROTOCOL_H
#define PROTOCOL_H

#define PROTOCOL_DELIMITER "|"
#define PROTOCOL_TERMINATOR "\n"

#define MESSAGE_WAIT "WAIT"
#define MESSAGE_WELCOME "WELCOME"
#define MESSAGE_START "START"
#define MESSAGE_MOVE "MOVE"
#define MESSAGE_PASS "PASS"
#define MESSAGE_QUIT "QUIT"
#define MESSAGE_BOARD "BOARD"
#define MESSAGE_YOUR_TURN "YOUR_TURN"
#define MESSAGE_OPPONENT_TURN "OPPONENT_TURN"
#define MESSAGE_VALID "VALID"
#define MESSAGE_INVALID "INVALID"
#define MESSAGE_OPPONENT_MOVE "OPPONENT_MOVE"
#define MESSAGE_OPPONENT_PASS "OPPONENT_PASS"
#define MESSAGE_GAME_OVER "GAME_OVER"
#define MESSAGE_OPPONENT_LEFT "OPPONENT_LEFT"
#define MESSAGE_ERROR "ERROR"

#define COLOR_BLACK "BLACK"
#define COLOR_WHITE "WHITE"

#define BOARD_SIZE 64

#define MAX_MESSAGE_LENGTH 512

typedef enum {
    MESSAGE_TYPE_WAIT,
    MESSAGE_TYPE_WELCOME,
    MESSAGE_TYPE_START,
    MESSAGE_TYPE_MOVE,
    MESSAGE_TYPE_PASS,
    MESSAGE_TYPE_QUIT,
    MESSAGE_TYPE_BOARD,
    MESSAGE_TYPE_YOUR_TURN,
    MESSAGE_TYPE_OPPONENT_TURN,
    MESSAGE_TYPE_VALID,
    MESSAGE_TYPE_INVALID,
    MESSAGE_TYPE_OPPONENT_MOVE,
    MESSAGE_TYPE_OPPONENT_PASS,
    MESSAGE_TYPE_GAME_OVER,
    MESSAGE_TYPE_OPPONENT_LEFT,
    MESSAGE_TYPE_ERROR,
    MESSAGE_TYPE_UNKNOWN
} MessageType;

typedef enum {
    PLAYER_COLOR_BLACK,
    PLAYER_COLOR_WHITE
} PlayerColor;

#endif
